pr: none
trigger: none

pool: Default

resources:
  webhooks:
    - webhook: case_sangeetha          ### Webhook alias
      connection: case_sangeetha    

steps:
- ${{ each value in parameters.secureFilesWebhook.listOfSecureFiles }}:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: ${{ value }}