pr: none
trigger: none

pool: Default

resources:
  webhooks:
    - webhook: case_sangeetha          ### Webhook alias
      connection: case_sangeetha    ### Incoming webhook service connection
      filters:
        - path: repositoryName      ### JSON path in the payload
          value: maven-releases     ### Expected value in the path provided
        - path: action
          value: CREATED

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    ### JSON payload data is available in the form of ${{ parameters.<WebhookAlias>.<JSONPath>}}
    script: |
      Write-Host ${{ parameters.case_sangeetha.repositoryName}}
      Write-Host ${{ parameters.case_sangeetha.component.group}}