pr: none
trigger: none

pool: Default

resources:
  webhooks:
    - webhook: case_amol          ### Webhook alias
      connection: case_amol_WebHook_usage    

steps:
- ${{ each value in parameters.secureFilesWebhook.listOfSecureFiles }}:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: ${{ value }}