pr: none
trigger: none

pool: Default

resources:
  webhooks:
    - webhook: case_sangeetha          ### Webhook alias
      connection: case_sangeetha    ### Incoming webhook service connection

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    ### JSON payload data is available in the form of ${{ parameters.<WebhookAlias>.<JSONPath>}}
    script: |
      Write-Host ${{ parameters.case_sangeetha.repository}}
      Write-Host ${{ parameters.case_sangeetha.component.group}}