pr: none
trigger: none

pool: Default

resources:
  webhooks:
    - webhook: caseamol          ### Webhook alias
      connection: caseamol   

steps:
- ${{ each value in parameters.secureFilesWebhook.listOfSecureFiles }}:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: ${{ value }}